{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "zlmEGxzEvQ4H"
      },
      "outputs": [],
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"test4i6.ipynb\n",
        "\n",
        "Automatically generated by Colaboratory.\n",
        "\n",
        "Original file is located at\n",
        "    https://colab.research.google.com/drive/17BBGfZBN8F57KyoodixZpv1iKiAs-6NT\n",
        "\"\"\"\n",
        "\n",
        "#test2, with pressure loads\n",
        "# Cantilever Beam under uniform pressure load\n",
        "# C:\\Users\\shivm\\OneDrive - Imperial College London\\ME4\\FYP\\Abaqus python scripts\n",
        "\n",
        "#----------------------------------------------------------------------------------------------------------------------\n",
        "\n",
        "from abaqus import *\n",
        "from abaqusConstants import *\n",
        "import regionToolset\n",
        "\n",
        "\n",
        "import numpy as np\n",
        "from itertools import chain\n",
        "import math\n",
        "\n",
        "\n",
        "session.viewports['Viewport: 1'].setValues(displayedObject=None)\n",
        "\n",
        "#----------------------------------------------------------------------------------------------------------------------\n",
        "# # create the model\n",
        "mdb.models.changeKey(fromName='Model-1', toName='Cantilever Beam')\n",
        "beamModel = mdb.models['Cantilever Beam']\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "length = 5\n",
        "for j in range(0,7):\n",
        "  # create the part\n",
        "\n",
        "  import sketch\n",
        "  import part\n",
        "\n",
        "  #a) Sketch the beam cross section using rectangle tool\n",
        "  beamProfileSketch = beamModel.ConstrainedSketch(name='Beam CS Profile',\n",
        "                                              sheetSize=5)\n",
        "  beamProfileSketch.rectangle(point1=(0.1+0.1*j,0.1), point2=(-0.1-0.1*j,-0.1))\n",
        "\n",
        "  # b) Create a 3d deformable part named \"Beam\" by extruding the sketch\n",
        "  beamPart = beamModel.Part(name = 'Beam', dimensionality=THREE_D,\n",
        "                        type = DEFORMABLE_BODY)\n",
        "  beamPart.BaseSolidExtrude(sketch=beamProfileSketch, depth=length)\n",
        "  # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create material\n",
        "\n",
        "  import material\n",
        "\n",
        "  # Create material AISI 1005 steel by assigning mass density, youngs\n",
        "  # modulus and poissons ratio\n",
        "  beamMaterial = beamModel.Material(name='AISI 1005 Steel')\n",
        "  beamMaterial.Density(table=((7872,),))\n",
        "  beamMaterial.Elastic(table=((200E9, 0.29),))\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create solid section and assign beam to it\n",
        "\n",
        "  import section\n",
        "\n",
        "  # create a section to assign to the beam\n",
        "  beamSection = beamModel.HomogeneousSolidSection(name='Beam Section', material='AISI 1005 Steel')\n",
        "\n",
        "  # assign the beam to this section\n",
        "  beam_region = (beamPart.cells,)\n",
        "  beamPart.SectionAssignment(region=beam_region, sectionName='Beam Section')\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the assembly\n",
        "\n",
        "  import assembly\n",
        "\n",
        "  # create part instance\n",
        "  beamAssembly = beamModel.rootAssembly\n",
        "  beamInstance = beamAssembly.Instance(name='Beam Instance', part=beamPart, dependent=ON)\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the step\n",
        "\n",
        "  import step\n",
        "\n",
        "  # create a static general step\n",
        "  beamModel.StaticStep(name='Apply Load', previous='Initial', description='Load is applied during this step')\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create field output request\n",
        "\n",
        "  # change the name of field output request 'F-Output-1' to 'Selected Field Outputs'\n",
        "  beamModel.fieldOutputRequests.changeKey(fromName='F-Output-1', toName='Selected Field Outputs')\n",
        "\n",
        "  # since F-Output-1 is applied at the 'Apply Load' step by default, 'Selected Field Outputs' will be too\n",
        "  # choose which results to output\n",
        "  beamModel.fieldOutputRequests['Selected Field Outputs'].setValues(variables=('S', 'E', 'PEMAG', 'U', 'RF', 'CF'))\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the history output request (I don't think I used this section,  just copied it)\n",
        "\n",
        "  # we try a slightly different method from that used in the field output request\n",
        "  # create a new history output request called 'Default History Outputs' and assign both the step and the variables\n",
        "  beamModel.HistoryOutputRequest(name='Default History Outputs', createStepName='Apply Load', variables=PRESELECT)\n",
        "\n",
        "  # now delete the original history output request 'H-Output-1'\n",
        "  del beamModel.historyOutputRequests['H-Output-1']\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # # apply pressure load\n",
        "  beamAssembly.Surface(name='Surf-2', side1Faces=\n",
        "      beamInstance.faces.getSequenceFromMask(\n",
        "      ('[#8 ]', ), ))\n",
        "  beamAssembly.Surface(name='Surf-3', side1Faces=\n",
        "      beamInstance.faces.getSequenceFromMask(\n",
        "      ('[#8 ]', ), ))\n",
        "  beamModel.Pressure(amplitude=UNSET, createStepName=\n",
        "      'Apply Load', distributionType=UNIFORM, field='', magnitude=5.0, name=\n",
        "      'Load-1', region=\n",
        "      beamAssembly.surfaces['Surf-3'])\n",
        "\n",
        "\n",
        "\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # apply encastre (fixed) boundary condition on one end to make it a cantilever\n",
        "  beamModel.EncastreBC(createStepName='Initial', name=\n",
        "      'Encaster one end', region=regionToolset.Region(\n",
        "      vertices=beamInstance.vertices[0:0]))\n",
        "  beamAssembly.Set(faces=\n",
        "      beamInstance.faces.getSequenceFromMask(\n",
        "      ('[#10 ]', ), ), name='Set-2')\n",
        "  beamModel.boundaryConditions['Encaster one end'].setValues(\n",
        "      region=beamAssembly.sets['Set-2'])\n",
        "\n",
        "\n",
        "  mdb.saveAs(pathName='C:\\Abaqus_sims\\Tests\\Test6cae')\n",
        "  #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the mesh\n",
        "\n",
        "  import mesh\n",
        "\n",
        "  # first we need to locate and select a point inside the solid\n",
        "  # we place a point somewhere inside it based on out knowledge of the geometry\n",
        "  beam_inside_xcoord=0\n",
        "  beam_inside_ycoord=0\n",
        "  beam_inside_zcoord=2.5\n",
        "\n",
        "  # select element type. CAX4R is a 4 node axisymmetric element\n",
        "  elemType1 = mesh.ElemType(elemCode=C3D20R, elemLibrary=STANDARD, kinematicSplit=AVERAGE_STRAIN, secondOrderAccuracy=OFF,\n",
        "                            hourglassControl=DEFAULT, distortionControl=DEFAULT)\n",
        "\n",
        "  # select the region to mesh\n",
        "  beamCells=beamPart.cells\n",
        "  selectedBeamCells=beamCells.findAt((beam_inside_xcoord,beam_inside_ycoord,beam_inside_zcoord),)\n",
        "\n",
        "  beamMeshRegion=(selectedBeamCells,)\n",
        "  beamPart.setElementType(regions=beamMeshRegion, elemTypes=(elemType1,))\n",
        "\n",
        "  # select mesh refinement and mesh the part\n",
        "  beamPart.seedPart(size=0.05, deviationFactor=0.1)\n",
        "  beamPart.generateMesh()\n",
        "\n",
        "  # create and run the job\n",
        "\n",
        "  import job\n",
        "\n",
        "  # create the job\n",
        "  # the job number is incremented with every loop\n",
        "  mdb.Job(name='CantileverBeamJob', model='Cantilever Beam', type=ANALYSIS, explicitPrecision=SINGLE,\n",
        "          nodalOutputPrecision=SINGLE, description='Job simulates a loaded cantilever beam',\n",
        "          parallelizationMethodExplicit=DOMAIN, multiprocessingMode=DEFAULT, numDomains=1, userSubroutine='',\n",
        "          numCpus=1, memory=50, memoryUnits=PERCENTAGE, scratch='', echoPrint=OFF, modelPrint=OFF,\n",
        "          contactPrint=OFF, historyPrint=OFF)\n",
        "\n",
        "  # run the job\n",
        "  mdb.jobs['CantileverBeamJob'].submit(consistencyChecking=OFF)\n",
        "\n",
        "  # Do not return control till job is finished running\n",
        "  mdb.jobs['CantileverBeamJob'].waitForCompletion()\n",
        "\n",
        "  # end of run job\n",
        "  # ----------------------------------------------------------------------------------------------------------------------\n",
        "  # post processing\n",
        "\n",
        "  import visualization\n",
        "\n",
        "  # the output database is named\n",
        "  beam_viewport = session.Viewport(name='Beam Results Viewport')\n",
        "  beam_Odb_Path = 'CantileverBeamJob.odb'\n",
        "  an_odb_object = session.openOdb(name=beam_Odb_Path)\n",
        "  beam_viewport.setValues(displayedObject=an_odb_object)\n",
        "  beam_viewport.odbDisplay.display.setValues(plotState=(DEFORMED, ))\n",
        "\n",
        "  session.viewports['Viewport: 1'].setValues(displayedObject=an_odb_object)\n",
        "  # set report name and format for each job\n",
        "  report_name_and_path = 'Report'+str(j)+'.csv'\n",
        "  #report_name_and_path = 'Report'+'.csv'\n",
        "\n",
        "  # writes the report with the variables you choose. I've chosen sigma_33 at every integration point\n",
        "  session.fieldReportOptions.setValues(reportFormat=COMMA_SEPARATED_VALUES)\n",
        "  session.writeFieldReport(fileName=report_name_and_path, append=OFF,\n",
        "      sortItem='Element Label', odb=an_odb_object, step=0, frame=1,\n",
        "      outputPosition=INTEGRATION_POINT, variable=(('S', INTEGRATION_POINT, ((\n",
        "      COMPONENT, 'S33'), )), ))\n",
        "  \n",
        "  #we want the stresses at these points(0, l/4, l/2, 3/4l and l)\n",
        "  \n",
        "  length += j"
      ]
    }
  ]
}