{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "KQcRjZpuakek"
      },
      "outputs": [],
      "source": [
        "# -*- coding: utf-8 -*-\n",
        "\"\"\"test4i6.ipynb\n",
        "\n",
        "Automatically generated by Colaboratory.\n",
        "\n",
        "Original file is located at\n",
        "    https://colab.research.google.com/drive/17BBGfZBN8F57KyoodixZpv1iKiAs-6NT\n",
        "\"\"\"\n",
        "\n",
        "#test2, with pressure loads\n",
        "# Cantilever Beam under uniform pressure load\n",
        "# C:\\Users\\shivm\\OneDrive - Imperial College London\\ME4\\FYP\\Abaqus python scripts\n",
        "\n",
        "#----------------------------------------------------------------------------------------------------------------------\n",
        "\n",
        "from abaqus import *\n",
        "from abaqusConstants import *\n",
        "import regionToolset\n",
        "\n",
        "\n",
        "import numpy as np\n",
        "from itertools import chain\n",
        "import math\n",
        "\n",
        "\n",
        "session.viewports['Viewport: 1'].setValues(displayedObject=None)\n",
        "\n",
        "#----------------------------------------------------------------------------------------------------------------------\n",
        "# # create the model\n",
        "# mdb.models.changeKey(fromName='Model-1', toName='Cantilever Beam')\n",
        "# beamModel = mdb.models['Cantilever Beam']\n",
        "mdb.models.changeKey(fromName='Model-1', toName='Plate_model')\n",
        "plateModel = mdb.models['Plate_model']\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "for j in range(0,6):\n",
        "  # create the part\n",
        "\n",
        "  import sketch\n",
        "  import part\n",
        "\n",
        "  #a) Sketch the beam cross section using rectangle tool\n",
        "  plateProfileSketch = plateModel.ConstrainedSketch(name='Plate CS Profile',\n",
        "                                              sheetSize=200)\n",
        "  plateProfileSketch.rectangle(point1=(-100, 100), point2=(100, -100))\n",
        "\n",
        "  plateProfileSketch.CircleByCenterPerimeter(center=(\n",
        "    0.0, 0.0), point1=(-10.0, 0.0))\n",
        "  \n",
        "\n",
        "  plateProfileSketch.RadialDimension(curve=\n",
        "    plateProfileSketch.geometry[6], radius=10+10*j, \n",
        "    textPoint=(-71.4530639648438, 0.294061660766602))\n",
        "\n",
        "  # b) Create a 3d deformable part named \"plate\" by extruding the sketch\n",
        "  platePart = plateModel.Part(dimensionality=TWO_D_PLANAR, name='Plate', type=\n",
        "    DEFORMABLE_BODY)\n",
        "  platePart.BaseShell(sketch=plateProfileSketch)\n",
        "\n",
        "    \n",
        "  \n",
        "\n",
        "  \n",
        "#   # # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create material\n",
        "\n",
        "  import material\n",
        "\n",
        "  # Create material AISI 1005 steel by assigning mass density, youngs\n",
        "  # modulus and poissons ratio\n",
        "  plateMaterial = plateModel.Material(name='AISI 1005 Steel')\n",
        "  plateMaterial.Density(table=((7872,),))\n",
        "  plateMaterial.Elastic(table=((200E9, 0.29),))\n",
        "\n",
        "  \n",
        "\n",
        "#   # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # # create solid section and assign beam to it\n",
        "\n",
        "  import section\n",
        "\n",
        "  # create a section to assign to the beam\n",
        "  PlateSection = plateModel.HomogeneousSolidSection(name='Plate Section', material='AISI 1005 Steel'\n",
        "  , thickness=None)\n",
        "\n",
        "  # assign the plate to this section\n",
        "  platePart.Set(faces=platePart.faces.getSequenceFromMask((\n",
        "    '[#1 ]', ), ), name='Set-4')\n",
        "  platePart.SectionAssignment(offset=0.0, offsetField='', offsetType=MIDDLE_SURFACE, region=\n",
        "    platePart.sets['Set-4'], sectionName='Plate Section', thicknessAssignment=FROM_SECTION)\n",
        "\n",
        "  \n",
        "\n",
        "#   # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the assembly\n",
        "\n",
        "  import assembly\n",
        "\n",
        "  # create part instance\n",
        "  plateAssembly = plateModel.rootAssembly\n",
        "  plateInstance = plateAssembly.Instance(name='Plate Instance', part=platePart, dependent=ON)\n",
        "\n",
        "  \n",
        "\n",
        "#   # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the step\n",
        "\n",
        "  import step\n",
        "\n",
        "  # create a static general step\n",
        "  plateModel.StaticStep(name='Step-1', previous='Initial', description='Step-1')\n",
        " \n",
        "  # plateAssembly.Set(cells=\n",
        "  #   plateInstance.cells.getSequenceFromMask(\n",
        "  #   ('[#1 ]', ), ), name='Set-1')\n",
        "\n",
        "  \n",
        "#   # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create field output request\n",
        "\n",
        "  # change the name of field output request 'F-Output-1' to 'Selected Field Outputs'\n",
        "  plateModel.fieldOutputRequests.changeKey(fromName='F-Output-1', toName='Selected Field Outputs')\n",
        "\n",
        "  # since F-Output-1 is applied at the 'Apply Load' step by default, 'Selected Field Outputs' will be too\n",
        "  # choose which results to output\n",
        "  plateModel.fieldOutputRequests['Selected Field Outputs'].setValues(variables=('S', 'E', 'PEMAG', 'U', 'RF', 'CF'))\n",
        "\n",
        "  \n",
        "\n",
        "#   # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the history output request (I don't think I used this section,  just copied it)\n",
        "\n",
        "  # we try a slightly different method from that used in the field output request\n",
        "  # create a new history output request called 'Default History Outputs' and assign both the step and the variables\n",
        "  plateModel.HistoryOutputRequest(name='Default History Outputs', createStepName='Step-1', variables=PRESELECT)\n",
        "\n",
        "  # now delete the original history output  request 'H-Output-1'\n",
        "  del plateModel.historyOutputRequests['H-Output-1']\n",
        "\n",
        "  \n",
        "\n",
        "#   # # #----------------------------------------------------------------------------------------------------------------------\n",
        "\n",
        "  v1 = plateInstance.vertices\n",
        "  verts1 = v1.getSequenceFromMask(mask=('[#8 ]', ), )\n",
        "  region = plateAssembly.Set(vertices=verts1, name='Set-1')\n",
        "\n",
        "  plateModel.DisplacementBC(name='BC-1', createStepName='Initial', \n",
        "      region=region, u1=SET, u2=UNSET, ur3=SET, amplitude=UNSET, \n",
        "      distributionType=UNIFORM, fieldName='', localCsys=None)\n",
        "\n",
        "  verts1 = v1.getSequenceFromMask(mask=('[#10 ]', ), )\n",
        "  region = plateAssembly.Set(vertices=verts1, name='Set-2')\n",
        "\n",
        "  session.viewports['Viewport: 1'].view.setValues(nearPlane=253.793, \n",
        "      farPlane=311.893, width=205.342, height=94.2157, cameraPosition=(19.9893, \n",
        "      -7.01929, 282.843), cameraTarget=(19.9893, -7.01929, 0))\n",
        "\n",
        "  session.viewports['Viewport: 1'].view.setValues(nearPlane=253.825, \n",
        "      farPlane=311.861, width=205.368, height=94.2276, cameraPosition=(20.6716, \n",
        "      -7.01929, 282.843), cameraTarget=(20.6716, -7.01929, 0))\n",
        "  session.viewports['Viewport: 1'].view.setValues(nearPlane=253.825, \n",
        "      farPlane=311.861, cameraUpVector=(0.00070316, 1, 0))\n",
        "\n",
        "\n",
        "  e1 = plateInstance.edges\n",
        "  edges1 = e1.getSequenceFromMask(mask=('[#8 ]', ), )\n",
        "  region = plateAssembly.Set(edges=edges1, name='Set-3')\n",
        "  plateModel.DisplacementBC(name='BC-3', createStepName='Initial', \n",
        "      region=region, u1=UNSET, u2=SET, ur3=UNSET, amplitude=UNSET, \n",
        "      distributionType=UNIFORM, fieldName='', localCsys=None)\n",
        "  session.viewports['Viewport: 1'].view.setValues(nearPlane=253.662, \n",
        "      farPlane=312.024, width=218.337, height=100.178, viewOffsetX=5.85374, \n",
        "      viewOffsetY=0.0599978)\n",
        "  session.viewports['Viewport: 1'].assemblyDisplay.setValues(step='Step-1')\n",
        "  session.viewports['Viewport: 1'].view.setValues(nearPlane=244.45, \n",
        "      farPlane=321.236, width=286.696, height=131.543, viewOffsetX=-6.23524, \n",
        "      viewOffsetY=-10.4826)\n",
        "#    # #----------------------------------------------------------------------------------------------------------------------\n",
        "\n",
        "#     #pressure load\n",
        "  s1 = plateInstance.edges\n",
        "  side1Edges1 = s1.getSequenceFromMask(mask=('[#2 ]', ), )\n",
        "  region = plateAssembly.Surface(side1Edges=side1Edges1, name='Surf-1')\n",
        "  plateModel.Pressure(name='Load-1', createStepName='Step-1', \n",
        "      region=region, distributionType=UNIFORM, field='', magnitude=-1.0, \n",
        "      amplitude=UNSET)\n",
        "\n",
        "\n",
        "  \n",
        "\n",
        "  \n",
        "#   #----------------------------------------------------------------------------------------------------------------------\n",
        "  # create the mesh\n",
        "\n",
        "  import mesh\n",
        "  platePart.setElementType(elemTypes=(mesh.ElemType(\n",
        "      elemCode=CPS4R, elemLibrary=STANDARD, secondOrderAccuracy=OFF, \n",
        "      hourglassControl=DEFAULT, distortionControl=DEFAULT), mesh.ElemType(\n",
        "      elemCode=CPS3, elemLibrary=STANDARD)), regions=(\n",
        "      platePart.faces.getSequenceFromMask((\n",
        "      '[#1 ]', ), ), ))\n",
        "  platePart.seedPart(deviationFactor=0.1, \n",
        "      minSizeFactor=0.1, size=1.0)\n",
        "  platePart.generateMesh()\n",
        "  platePart.deleteMesh(regions=\n",
        "      platePart.faces.getSequenceFromMask((\n",
        "      '[#1 ]', ), ))\n",
        "  platePart.seedEdgeBySize(constraint=FINER, \n",
        "      deviationFactor=0.1, edges=\n",
        "      platePart.edges.getSequenceFromMask((\n",
        "      '[#1 ]', ), ), minSizeFactor=0.1, size=0.5)\n",
        "  platePart.generateMesh()\n",
        "\n",
        "  \n",
        "  \n",
        "  \n",
        "\n",
        "  \n",
        "\n",
        "  \n",
        " # #----------------------------------------------------------------------------------------------------------------------\n",
        "  # # # create and run the job\n",
        "\n",
        "  import job\n",
        "\n",
        "  # create the job\n",
        "  # the job number is incremented with every loop\n",
        "  mdb.Job(name='PlateJob', model='Plate_model', type=ANALYSIS, explicitPrecision=SINGLE,\n",
        "          nodalOutputPrecision=SINGLE, description='Job simulates a loaded plate',\n",
        "          parallelizationMethodExplicit=DOMAIN, multiprocessingMode=DEFAULT, numDomains=1, userSubroutine='',\n",
        "          numCpus=1, memory=50, memoryUnits=PERCENTAGE, scratch='', echoPrint=OFF, modelPrint=OFF,\n",
        "          contactPrint=OFF, historyPrint=OFF)\n",
        "  \n",
        "  mdb.Job(name='PlateJob', model='Plate_model', type=ANALYSIS, explicitPrecision=SINGLE,\n",
        "    description='Job simulates a loaded plate',\n",
        "    atTime=None, contactPrint=OFF, echoPrint=OFF,\n",
        "    getMemoryFromAnalysis=True, historyPrint=OFF, \n",
        "    memory=90, memoryUnits=PERCENTAGE, modelPrint=OFF, \n",
        "    multiprocessingMode=DEFAULT, nodalOutputPrecision=SINGLE, \n",
        "    numCpus=1, numGPUs=0, queue=None, resultsFormat=ODB, scratch='',\n",
        "    userSubroutine='', waitHours=0, waitMinutes=0)\n",
        "\n",
        "  # run the job\n",
        "  mdb.jobs['PlateJob'].submit(consistencyChecking=OFF)\n",
        "\n",
        "  # Do not return control till job is finished running\n",
        "  mdb.jobs['PlateJob'].waitForCompletion()\n",
        "\n",
        "  \n",
        "\n",
        "\n",
        "  # # end of run job\n",
        "  # # ----------------------------------------------------------------------------------------------------------------------\n",
        "  # # post processing\n",
        "\n",
        "  import visualization\n",
        "\n",
        "  # the output database is named\n",
        "  beam_viewport = session.Viewport(name='Beam Results Viewport')\n",
        "  beam_Odb_Path = 'PlateJob.odb'\n",
        "  an_odb_object = session.openOdb(name=beam_Odb_Path)\n",
        "  beam_viewport.setValues(displayedObject=an_odb_object)\n",
        "  beam_viewport.odbDisplay.display.setValues(plotState=(DEFORMED, ))\n",
        "\n",
        "  session.viewports['Viewport: 1'].setValues(displayedObject=an_odb_object)\n",
        "  # set report name and format for each job\n",
        "  report_name_and_path = 'Report'+str(j)+'.csv'\n",
        "  #report_name_and_path = 'Report'+'.csv'\n",
        "\n",
        "  # writes the report with the variables you choose. I've chosen sigma_33 at every integration point\n",
        "  session.fieldReportOptions.setValues(reportFormat=COMMA_SEPARATED_VALUES)\n",
        "  session.writeFieldReport(fileName=report_name_and_path, append=OFF,\n",
        "      sortItem='Element Label', odb=an_odb_object, step=0, frame=1,\n",
        "      outputPosition=INTEGRATION_POINT, variable=(('S', INTEGRATION_POINT, ((\n",
        "      COMPONENT, 'S22'), )), ))\n",
        "  mdb.saveAs(pathName='C:\\Abaqus_sims\\Plate\\SCcripts\\Script1\\Test11\\Testcae')\n",
        "\n",
        "\n",
        "  \n",
        "\n",
        "\n",
        "  \n",
        "  \n"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
